### ISSUE TITLE
New ARTIQ Python compiler post-merge checklist

### ISSUE THREAD

**Issue by whitequark** [m-labs/artiq#177]
The post-merge part of https://github.com/m-labs/artiq/issues/86 and unittest failures.
  - [x] call `watchdog_set` and `watchdog_clear`
  - [x] loop unrolling
  - [x] unification of empty lists in attributes
  - [x] lattice issue in `test_rtt (artiq.test.coredevice.rtio.CoredeviceTest)`
  - [x] assert in `test_misc (artiq.test.coredevice.portability.HostVsDeviceCase)`
  - [x] mapping of exceptions not derived from ARTIQException to core device and back
  - [x] resynchronization of attributes before kernel return

**Comment by sbourdeauducq** [comment]
Fraction is very low-priority, the other two are important.

**Comment by whitequark** [comment]
Done
