### ISSUE TITLE
Rust runtime meta-issue

### ISSUE THREAD

**Issue by whitequark** [m-labs/artiq#569]
Needed for feature parity, with almost-only-Rust on comms CPU (there will still be `-lcompiler-rt`+`-lalloc` needed by Rust and `-lbase` needed by lwip):
- [x] Port watchdogs
- [x] Port cache
- [x] Allow sessions to interrupt one another (magic_ok codepath)
- [x] Port idle kernels
- [x] Port startup kernels
- [x] Set SOF_KEEPALIVE on bind PCB
- [x] Add rustc --cfg support to misoc CSR generator
- [x] Port moninj
- [x] Port analyzer
- [x] Port RPCs
- [x] Remove initial length field to allow streaming requests
- [x] Port isr/uart.h
- [x] Use a string interner for exceptions
- [x] Port network_init()
- [x] Port/rewrite flash_storage

Needed for feature parity, with almost-only-Rust on kernel CPU:
- [x] Port DDS (to ARTIQ Python)
- [x] Port I2C (to ARTIQ Python?)
- [x] Port RTIO
- [x] Port artiq_personality

Needed for completeness:
- [x] Remove \0 from strings sent over the network
- [x] Confine comms CPU stuff to bottom 4M of memory instead of having it all around
- [x] Use 64-bit integers for watchdog ms
- [x] Align RPC allocas to 4 bytes
- [x] Use Pascal strings in ARTIQ Python
- [x] ~~TMPU support~~
- [x] ~~Remove allocation when receiving kernel~~
- [x] ~~Fully safe mailbox interface~~

Upstreaming:
- [x] ~~Extract core_error~~
- [x] ~~Fix problems with core_io and make it use core_error~~
- [x] ~~Make byteorder use core_io and core_error~~
- [x] ~~Stack probe fixes in LLVM (https://reviews.llvm.org/D9653)~~

**Comment by sbourdeauducq** [comment]
> Remove \0 from strings sent over the network

What is that for exactly?

**Comment by whitequark** [comment]
Rust uses Pascal strings, not C strings, so that's just some junk that gets added on one end and removed on another.

**Comment by whitequark** [comment]
> Remove allocation when receiving kernel

This turned out not to be possible because the shared objects we generate aren't execute-in-place (they have holes and that needs an MMU if we really want to do it zero-copy).

**Comment by whitequark** [comment]
> Fully safe mailbox interface

I've evaluated this and, while possible, this conversion is unlikely to prevent more bugs than it would cause.

**Comment by whitequark** [comment]
> Extract core_error
>  Fix problems with core_io and make it use core_error
>  Make byteorder use core_io and core_error

I've looked into it and core_io/core_error are very annoying to write, mostly because you have to manually produce patches for dozens of libstd versions. I'm not going to die on this hill, especially seeing as the workaround is mild. Someone else in the community is going to have to be annoyed enough.

**Comment by whitequark** [comment]
Runtime has been migrated to Rust.
