### ISSUE TITLE
New ARTIQ Python compiler pre-merge checklist

### ISSUE THREAD

**Issue by whitequark** [m-labs/artiq#86]
Currently the new compiler misses many features at edges, often subtle. This issue is intended to track them to ensure none are forgotten.

  - [x] RPC return type annotations
  - [x] emission of debug info via LLVM
  - [x] symbolization of core device backtraces
  - [x] `syscall`
  - [x] `artiq.language.core.int64` → `artiq.language.core.int(width=64)`
  - [x] classes and methods
  - [x] add proper debug location to llvmlite IRBuilder
  - [x] generate `sret` when returning structures
  - [x] re-enable LocalAccessValidator
  - [x] embedding of foreign objects
  - [x] call `now_init` and `now_save`
  - [x] interleaving

**Comment by sbourdeauducq** [comment]
Interleaving, classes and syscalls are by far the highest priority as users cannot do anything with the new compiler until this is done.

We don't need to keep compatibility with ``artiq.language.core.int64``. Removing it is good.

**Comment by whitequark** [comment]
Merged.
